# Generated by Django 5.0.4 on 2024-04-19 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='photo',
            name='category',
        ),
        migrations.DeleteModel(
            name='category',
        ),
        migrations.DeleteModel(
            name='photo',
        ),
    ]
