# Generated by Django 5.0.4 on 2024-04-20 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=100)),
                ('Phone_number', models.CharField(max_length=100)),
                ('Email_id', models.EmailField(max_length=254)),
                ('Booing_date', models.DateField()),
                ('functionname', models.CharField(max_length=100)),
                ('expectingbudjet', models.CharField(max_length=1000000000)),
            ],
        ),
    ]
