# Generated by Django 5.0.4 on 2024-04-20 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0004_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='fullname',
            new_name='full_name',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='expectingbudjet',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='functionname',
        ),
    ]
