# Generated by Django 5.0.4 on 2024-04-21 02:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0005_rename_fullname_booking_full_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='category',
            field=models.CharField(choices=[('a', 'marrage'), ('b', 'birthday'), ('c', 'reception'), ('d', 'engagement'), ('e', 'govt.ceremony')], max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='Phone_number',
            field=models.IntegerField(),
        ),
    ]
