# Generated by Django 5.0.4 on 2024-04-21 07:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0006_booking_address_booking_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='reviewrating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('review', models.TextField(blank=True, max_length=500)),
                ('rating', models.FloatField()),
                ('suggestions', models.CharField(max_length=500)),
                ('Email_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evenapp.booking')),
            ],
        ),
    ]
