# Generated by Django 5.0.4 on 2024-04-21 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0007_reviewrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='Email_id',
            field=models.EmailField(max_length=254),
        ),
    ]
