# Generated by Django 5.0.4 on 2024-04-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0008_alter_reviewrating_email_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewrating',
            name='rating',
            field=models.IntegerField(default=0),
        ),
    ]
