# Generated by Django 5.0.4 on 2024-04-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0011_review_delete_reviewrating'),
    ]

    operations = [
        migrations.CreateModel(
            name='client_service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('details', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.CharField(max_length=500),
        ),
    ]
