# Generated by Django 5.0.4 on 2024-04-23 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0013_alter_booking_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(default='N/A', max_length=500),
        ),
    ]
