# Generated by Django 5.0.4 on 2024-04-24 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0020_delete_services_alter_booking_address'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=20)),
                ('mobile', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='address',
            field=models.CharField(max_length=200),
        ),
    ]
