# Generated by Django 5.0.4 on 2024-04-24 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evenapp', '0021_contact_alter_booking_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='place',
            field=models.CharField(default=2, max_length=100),
            preserve_default=False,
        ),
    ]
